# Generated by Django 2.1.5 on 2019-05-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampeonM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cantVida', models.IntegerField()),
                ('cantArmadura', models.IntegerField()),
                ('cantMR', models.IntegerField()),
                ('carril', models.CharField(max_length=40)),
                ('cantDamageI', models.IntegerField()),
            ],
        ),
    ]
